package com.cbfacademy.restapiexercise.ious;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;


@Entity
@Table(name = "ious")
    
public class IOU {
    
// defined a simple entity

    // @GeneratedValue(strategy=GenerationType.UUID
    @Id // setting the Id column as primary key  
    @GeneratedValue(strategy=GenerationType.AUTO) //  // setting autogenerate on Id column
    private UUID id; // UUID is autogenerated with a mixture of methods in it
    private String borrower;
    private String lender;
    private BigDecimal amount;
    private Instant dateTime;

    public IOU (String borrower, String lender, BigDecimal amount, Instant dateTime){
        this.borrower = borrower;
        this.lender = lender;
        this.amount = amount;
        this.dateTime = dateTime;
    }

    // creating getters and setters for each field, except id, which should only have a getter
    public UUID getId(){
        return this.id;
    }

    public String getBorrower(){
        return this.borrower;
    } 
    
    public String getLender(){
        return this.lender;
    }
    
    public BigDecimal getAmount(){
        return this.amount;
    }    

    public Instant getDateTime(){
        return this.dateTime;
    }

    // creating setters for each field, except id, which should only have a getter    
    public void setBorrower(String borrower){
        this.borrower = borrower;
    } 
    
    public void setLender(String lender){
        this.lender = lender;
    }
    
    public void setAmount(BigDecimal amount){
        this.amount = amount;
    }    

    public void setDateTime(Instant dataTime){
        this.dateTime = dateTime;
    }

}
