package com.cbfacademy.restapiexercise.ious;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;


@Entity
@Table(name = "ious")
    
public class IOU {
    
    // amended 24/8/2024 and added
    // @Column(columnDefinition = "VARCHAR (36)") 
    // @JdbcTypeCode(SqlTypes.VARCHAR) in order for Spring Boot
    // to map UUID fields to text-based columns instead of BINARY
    // columns where the Id was begn stored as "BLOB" in the database
    // defined a simple entity
    @Id // setting the Id column as primary key  
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(columnDefinition = "VARCHAR (36)") // added 24/8/2024 to prevent mapping of UUID fields to BINARY columns in MySql
    @JdbcTypeCode(SqlTypes.VARCHAR) // added 24/8/2024 to prevent mapping of UUID fields to BINARY columns in MySql
    //@GeneratedValue(strategy=GenerationType.AUTO) //  setting autogenerate on Id column
    private UUID id; // UUID is autogenerated with a mixture of methods in it
    private String borrower;
    private String lender;
    private BigDecimal amount;
    private Instant dateTime;

    public IOU() {
        this(null, null, BigDecimal.ZERO, Instant.now());
    }

    public IOU (String borrower, String lender, BigDecimal amount, Instant dateTime){
        this.borrower = borrower;
        this.lender = lender;
        this.amount = amount;
        this.dateTime = dateTime;
    }

    // Define a default UUID - suggested by Kelly -CBF group member
    private static final UUID DEFAULT_UUID = UUID.fromString("00000000-0000-0000-0000-000000000000");

    // creating getters and setters for each field, except id, which should only have a getter
    // public UUID getId(){
    //     return this.id;
    // }


    //- suggested by Kelly -CBF group member
    public UUID getId() {

        return id != null ? id : DEFAULT_UUID;
    }


    public String getBorrower(){
        return this.borrower;
    } 
   
    public void setBorrower(String borrower){
        this.borrower = borrower;
    } 
    

    public String getLender(){
        return this.lender;
    }

    public void setLender(String lender){
        this.lender = lender;
    }

    
    public BigDecimal getAmount(){
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount){
        this.amount = amount;
    } 

    
    public Instant getDateTime(){
        return this.dateTime;
    }    

    public void setDateTime(Instant dataTime){

    }

}
